version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-javascript-plugin
    steps:
      - checkout
      - run:
          command: git clone git@github.com:orbs-network/orbs-network-go.git --branch master --single-branch .
          working_directory: /home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go
      - run:
          command: ./docker/build/build-docker-node.sh
          working_directory: /home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go
          environment:
            BUILD_FLAG: javascript
      - run:
          command: ./docker/build/build-docker-gamma.sh
          working_directory: /home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go
          environment:
            BUILD_FLAG: javascript
      - run: ./docker-build.sh
      - run: ./release/build.sh
      - run: ./e2e.sh
      - run: ./release/release.sh
